### ISSUE TITLE
"Setup a new code" not working

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#131]
**Describe the bug**
When I click on the "Setup a new code" button:

![setup](https://user-images.githubusercontent.com/16132028/135894107-66f6aedf-ea6b-49c8-90e9-d4d7a99d4945.png)

I get a 404:

![404](https://user-images.githubusercontent.com/16132028/135894129-d7251eb3-90f8-4391-aa28-15e7cd055730.png)

**To Reproduce**
Click on the button. My url, as a reference, is [this](https://aiidalab-demo.materialscloud.org/user/giovanni.pizzi@epfl.ch/apps/apps/aiidalab-widgets-base/notebooks/setup_code.ipynb?label=pw&plugin=quantumespresso.pw&computer=localhost&description=pw.x%20in%20AiiDAlab%20container.&input_plugin=quantumespresso.pw&remote_abs_path=/usr/bin/pw.x)

**Screenshots**
See above

**Comment by giovannipizzi** [comment]
Mmm, not sure why I was running on aiidalab-demo... Anyway, the problem there exists, and the version is v21.10.0b1

**Comment by csadorf** [comment]
So the issue occurs because of this change: https://github.com/aiidalab/aiidalab-widgets-base/pull/229

To reproduce one needs to install the aiidalab-widgets-base app in version `1.0.0rc2` or `1.0.0rc3`.
```
$ aiidalab install aiidalab-widgets-base==1.0.0rc3 --pre
```

It is resolved as of version `1.0.0rc4` and in the `1.0.0` release version.

As a general note, this points to a bit of a larger problem of how to _safely_ rely on other apps, i.e., inter-app dependencies. I believe that the library-dependency problem is largely solved, but inter-app dependencies with potentially changing endpoints are still challenging. We do have the `aiidalab` package that can give us the information about installed versions etc., so in principle it should be possible for us to declare inter-app dependencies and detect incompatibilities.
