### ISSUE TITLE
Why remove StructureExampleWidget?

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#152]
Is there any reason why you remove `StructureExampleWidget` from structure_manerger_widget importer?

**Comment by csadorf** [comment]
Yes, Nicola did not like it.

**Comment by unkcpz** [comment]
Well, it is a useful feature during developing.

**Comment by csadorf** [comment]
I agree. What is your opinion on this @giovannipizzi ?

**Comment by giovannipizzi** [comment]
I also would be in favour of keeping it - it's always better to have something easy to quickly test without thinking/clicking too much. Indeed, Nicola did not like it, I think. Maybe two things:
- extend it not to have only Si and SiO2, but also 3-4 more complex structures that don't just look like a demo
- make it easy to have it optionally, so it's on in "debug" mode (e.g. pre-releases) but not there for releases or something similar (if really Nicola does not want it - otherwise I'd keep it; it's also true that with optimade, it's quite easy to pick an example structure, even if it's still 10 clicks instead of 2...)

**Comment by csadorf** [comment]
> extend it not to have only Si and SiO2, but also 3-4 more complex structures that don't just look like a demo

That's probably the right move. 👍 

> make it easy to have it optionally, so it's on in "debug" mode (e.g. pre-releases) but not there for releases or something similar (if really Nicola does not want it - otherwise I'd keep it; it's also true that with optimade, it's quite easy to pick an example structure, even if it's still 10 clicks instead of 2...)

I would prefer to avoid this if possible.

**Comment by unkcpz** [comment]
> extend it not to have only Si and SiO2,

For debug purposes, I would suggest also including Au for metal.
