### ISSUE TITLE
Allow to use other pseudopotentials

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#201]
**Is your feature request related to a problem? Please describe.**
Currently, only the SSSP pseudopotentials are configurable for the workflow. The proper choice of pseudopotential has impact on the results in many different cases more than just the accuracy and performance. For example, without non-linear core correction (NLCC) the NaCl is a semi-metal. 

**Describe the solution you'd like**
Add a pseudopotential selection widget to allow users to upload or set the pseudopotential by url.

**Describe alternatives you've considered**
Other pseudopotential families in setting step, more than just the SSSP libraries. This is more easy to implemented since the aiida-pseudo already contains the pseudo-dojo. But it is not versatile as the solution above.

This issue can be tackled in two:
- [x] support more families, such as pseudo-dojo, which has been done in https://github.com/aiidalab/aiidalab-qe/issues/366
- [x] User can upload a customized pseudo to use https://github.com/aiidalab/aiidalab-qe/pull/435

**Comment by AndresOrtegaGuerrero** [comment]
I think it will be nice that the app also considers the family of pseudo-dojo, then the user can conduct simulations with spin-orbit coupling

**Comment by unkcpz** [comment]
@AndresOrtegaGuerrero thanks for the suggestion. 
But I think the pseudo-dojo library with relativistic pseudopotentanils is not included in the aiida-pseudo, and that is what is needed for SOC calculation. 
The other issue is that the QeApp based on setting the parameters for the protocols that are not well-tested for SOC calculation, it may problematic to use the same protocol for SOC calculation. 
cc @mbercx for commont.

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz I think you can install pseudo dojo and you can select if you want the full-relativistic ones. 
I think like this `aiida-pseudo install pseudo-dojo -r FR -f upf -x PBE -p stringent -s normal`
And maybe if the app includes an option of doing SOC simulation, it selects a predefined protocol for SOC?

**Comment by mbercx** [comment]
As @AndresOrtegaGuerrero mentioned, I think you can install all pseudo-dojo configurations with `aiida-pseudo`, so that shouldn't be a problem. Installing all the configurations can take a bit of time though, but they are currently installed in the background I believe?

Regarding the protocol: since I have very little experience with SOC calculations, I'm not sure how to adapt the protocols. This will potentially require quite a bit of testing to make sure we have input parameters that offer reasonable precision for most structures. We might first also want to be able to more flexibly set the starting magnetization first (https://github.com/aiidalab/aiidalab-qe/issues/238)?

Note that we have the `SpinType` enum to pass to the `get_builder_from_protocol()` method.

**Comment by unkcpz** [comment]
Yep! thanks.

closed by https://github.com/aiidalab/aiidalab-qe/pull/435
