### ISSUE TITLE
Orbital-resolved PDOS

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/aiidalab-qe#357]
**Is your feature request related to a problem? Please describe.**
I remember we discussed this at some point, but I cannot remember what we discussed or couldn't find an issue.
In some cases, I'd like also an orbital-resolved PDOS, and not only projected on atoms. E.g. if I have a single atom in the cell, the total DOS is == to the PDOS projected on that atom. But if I have s, p, d, ... orbitals, I'd like to be able to see (optionally) those components.

**Describe the solution you'd like**
Of course there are cases in which this makes things much more busy in the GUI and can become more confusing.
An option: have a toggle or checkbox in the widget, that says "orbital-resolved PDOS", and splits all PDOS into each channel.
So by default e.g. for GaAs yo would only have three curves (Total DOS, projected on Ga and on As), but activating that option you get all orbitals on each atom (Ga s, Ga p_x, Ga p_y, ...).

**Additional context**
I'm not sure if this should be implemented in the widget. Maybe it's better, as we already agreed, to keep instead the plot widget "dumb" and have the toggle in the AiiDAlab QE app; when the toggle is selected, the PDOS is recomputed and new data is sent to the widget, that will then redraw. @mbercx @unkcpz @dou-du what do you think? Is this possible? (Do we have orbital-resolved PDOS?)

**Comment by unkcpz** [comment]
> I remember we discussed this at some point, but I cannot remember what we discussed or couldn't find an issue.

I remember almost everything, don't worry. I implemented the code what you currently see for every position, which is far from perfect I admit. The conclusion of the discussion between you, me and Xing is we use that for temporary since we really want to use the new widget-bandsplot for magnetism dos. But sure, we need to move on to support a more versatile toggle way to plot the PDOS. You can also find discussion between me and @superstar54 at https://github.com/aiidalab/aiidalab-qe/pull/313

> but activating that option you get all orbitals on each atom (Ga s, Ga p_x, Ga p_y, ...).

I tried and the reason I didn't use this for the current "demo" viewer is once we have more than 2 atoms, the pdos become super messy that we have 9 pdos for every atom. To many legends is the panel which breaks the layout of the widget. 

For the implementation, I implement the code for drawing wrt projections of orbitals at https://github.com/aiidalab/aiidalab-qe/blob/2e4c7faa50240071e80d855969a49e0643154412/aiidalab_qe/node_view.py#L201-L216, which is not activate used in the QeApp, since we didn't pass the "projections" infor to the widget. 

I think it makes more sense this toggle is implemented in the QeApp rather than in bandsplot widget.

**Comment by unkcpz** [comment]
I think this can be regarded as addressed by https://github.com/aiidalab/aiidalab-qe/commit/f8695600762a2eb186963ab998fc5988f5cd90b4, feel free to reopen it. We will move to have a new bandsplot widget and only fix the critical issues for the current one.
