### ISSUE TITLE
Adapt installation process of pseudo families

### ISSUE THREAD

**Issue by mbercx** [aiidalab/aiidalab-qe#386]
AFAIK, currently the QE app installs the pseudopotential files in the background when the container starts. If the user comes to the submission part of the app before the installation is finished, the submission is blocked until the pseudos are installed.

One point is that we can work on already having the pseudos installed in the image, and/or have the pseudo archives in the image and install without having to download the files once https://github.com/aiidateam/aiida-pseudo/pull/135 is merged.

Perhaps we don't have to install _all_ configurations right away though. Maybe we can install the most commonly used ones by default, and if the user selects a more esoteric one, install the family from a local archive or download it upon submission.

From a discussion with @giovannipizzi and @unkcpz.

**Comment by unkcpz** [comment]
>  install the family from a local archive

The pseudo families are just the aiida groups so I think this is a very good idea to go with, this even not requires the `aiida-pseudo`, we can have the archives exported from groups for every pseudo library and import on requests.

**Comment by danielhollas** [comment]
Just noting as a non-QeApp user, I would be against significantly increasing the size of the aiidalab Docker image because of a single App. :-)

**Comment by mbercx** [comment]
> Just noting as a non-QeApp user, I would be against significantly increasing the size of the aiidalab Docker image because of a single App. :-) 

I think we can make it part of a QE-specific part of the stack? ^^ it's mainly vital that we find ways to improve the startup time for demo purposes.

**Comment by unkcpz** [comment]
> Just noting as a non-QeApp user, I would be against significantly increasing the size of the aiidalab Docker image because of a single App. :-)

Don't worry :smile: We'll keep it as a separate image, let's say `full-demo`? Then add QeApp from the start and then everything that will highlight its power, maybe include also your app @danielhollas ?

**Comment by danielhollas** [comment]
Sure, wasn't sure which image you have in mind. The problem with my app is that it depends on ORCA, which needs to be installed manually since it requires a license (so not great for automatic deployment unfortunately).

**Comment by unkcpz** [comment]
We now have pseudo-dojo and having a specific docker image for qeapp with pseudopotential libraries are downloaded to the container and installed when the app first-time start. 
The image size is sure a bit fat. 
-  download size `full-stack`: 794.06 MB and `qe`: 1.28 GB
- container size (after pull to docker) `full-stack`: 2.48GB and `qe`: 3.82 GB

For the online deployment, the image will download once and used for all running container, thus the download size is not such a huge problem. 
As for container size, it is larger than `full-stack` but compare to old `aiidalab-docker-stack` which require 4.87GB it is quite still quite slim. Since it brings more benefit for the user to start using app without any waiting when the first time app start. I think it is a reasonable sacrifice on image size.
