### ISSUE TITLE
Add and activate the tot_magnetization widget when running magnetic simulation on insulator 

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-qe#412]
```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
     Error in routine iosys (1):
     fixed occupations and lsda need tot_magnetization
 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```
when trying an insulator with magnetism. I think QE App should catch this and avoid QE to crash.

_Originally posted by @giovannipizzi in https://github.com/aiidalab/aiidalab-qe/issues/245#issuecomment-1579026933_

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz  I guess it can be together with the starting_magnetization widget and tags, otherwise the app gives the impression you can calculate antiferromagnetic cases.

**Comment by AndresOrtegaGuerrero** [comment]
@unkcpz Do we need like a new feature for tot_magnetization in qe app? because we don't have this feature

**Comment by unkcpz** [comment]
I think we can add it, it is quite easy from what I understand by just adding a widget for setting it, correct?

**Comment by AndresOrtegaGuerrero** [comment]
Ok i will update the widget! , though according to the manual in simulation we use `tot_magnetization` or  `starting_magnetization` so it has to be like one or the other  [tot_magnetization](https://www.quantum-espresso.org/Doc/INPUT_PW.html#tot_magnetization). However now that I read the issue, the problem is about selecting `insulator` with `magnetism` so i guess we also need to see the workchain , to check that a magnetization is defined if this combination is set.
