### ISSUE TITLE
Add search page

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#515]
In the last AiiDAlab meeting, we discussed the possible improvement for selecting (searching) the workchain. One good option would be the search page introduced by @cpignedoli .
In the case of aiidalab-qe, some special designs are needed:
- a way to show the properties calculated by the plugins.
- the search page itself could be a plugin, and we need to expose the entry point for the logo page of the QE.

Some other useful features:
- search by keywords (label, group, etc)

**Comment by cpignedoli** [comment]
I could present the search page's present status for us at the next meeting (simple but efficient).
If I need right now to extend it to the QE app I would have to proceed as follows:
the center point is a structure S
-if I compute a property of S with QE, I add to S extras the uuid of the workchain used
-the search app will look for Structures that have uuids in a specific extra field
-if S has a  uuid coming from QE, in the table of search results I put a link that passes to the QE app the specific workchain since the QE app is already the best viewer for QE results

**Comment by superstar54** [comment]
> I could present the search page's present status for us at the next meeting (simple but efficient).

Thanks! Yes, please. 
I will also play with the test search page.
