### ISSUE TITLE
Add button to display Results panel

### ISSUE THREAD

**Issue by mikibonacci** [aiidalab/aiidalab-qe#585]
The following is from a user's feedback:

"It would be nice to add a *Display results* button near the *Kill workchain* one. 
This will be more intuitive for a user, instead of wait the automatic display.
The user may think that something went wrong and the workchain failed."

Indeed, he guessed that his workchain was failed, but actually was `finished_ok`, and still loading results.

Pinning @unkcpz and @danielhollas for some feedback about this.

**Comment by unkcpz** [comment]
I remember @danielhollas mentioned his app didn't load the workchain viewer automatically but only show when a button was clicked, correct me if I am wrong.
I think a reasonable behavior would be always showing a workflow overview showing the current input/output summaries plus the state of the current workchain. 

I also remember @superstar54 had a very interesting demo showing how to use aiida engine monitor to show the updated result, but that is for the long term improvement. 
For the moment, I think we should adapt the way @danielhollas used for his app.

**Comment by superstar54** [comment]
I just discussed with @mikibonacci that this problem most probably happens in the Phonon plugin with a huge number of sub-processes, as reported in https://github.com/aiidalab/aiidalab-widgets-base/issues/584. We believe this should be fixed in https://github.com/aiidalab/aiidalab-widgets-base/pull/583. 

Besides, now there will be information on the job state close to the `kill` button, as implemented in https://github.com/aiidalab/aiidalab-qe/pull/648, so the user will not be confused anymore about the job's state.

Thus I closed this issue.
