### ISSUE TITLE
Expose convergence criteria to user in advanced settings

### ISSUE THREAD

**Issue by cpignedoli** [aiidalab/aiidalab-qe#611]
**Is your feature request related to a problem? Please describe.**
If you want to compute phonons for a "large system" say 100 or 150 atoms the "precise" convergence settings may be not precise enough

**Describe the solution you'd like**
Expose convergence thresholds in the advanced section

**Describe alternatives you've considered**
I do not have better alternatives in mind right now, an option button "do not scale convergence thr wrt system size" may not be practical

**Comment by AndresOrtegaGuerrero** [comment]
Perhaps to expose `etot_conv_thr` `forc_conv_thr` to be controlled by the user , when necessary

**Comment by unkcpz** [comment]
Me and @edan-bainglass had a discussion yesterday. It would be nice if all the parameters of protocol will be shown and able to be modified. The rough idea is that the UI looks like the `ComputationalResourcesWidget`, there will be a checkbox under each protocol to display the parameters in the editable widgets. 

It distinguish the two types of parameters, the "advanced setting" for parameters that not in the protocol yaml file of workflows and used by advanced user for advanced properties. The "protocol override settings" for parameters that override the protocols. 
Which means the k-distance will then moved to such "protocol override settings". 

Like this idea? :smile: @cpignedoli @AndresOrtegaGuerrero

**Comment by AndresOrtegaGuerrero** [comment]
The issue with this solution you suggest, is that i think you might lose provenance. Not all the parameters of the input are accesible as a dict in aiida-quantumespresso. On the other hand , it might require a change in PwBaseWorkChain, since https://github.com/aiidateam/aiida-quantumespresso/blob/b517686df8cd33765ef12cbf430620ea8e94f137/src/aiida_quantumespresso/workflows/pw/base.py#L178

These parameters are calculated based on the number of atoms in the structure.

**Comment by superstar54** [comment]
@cpignedoli Could you give more detail of the problem? The PW protocol uses [`conv_thr_per_atom`](https://github.com/aiidateam/aiida-quantumespresso/blob/b517686df8cd33765ef12cbf430620ea8e94f137/src/aiida_quantumespresso/workflows/protocols/pw/base.yaml#L39) to control the `etot_conv_thr`. So, in principle, the conv standard is the same for small and large systems.


> It distinguish the two types of parameters, the "advanced setting" for parameters that not in the protocol yaml file of workflows and used by advanced user for advanced properties.

Users may be confused about this. They need to remember which parameters belong to which. Otherwise, they need to go to two places to find and set the parameters. The current design, which only has the basic setting and the advanced setting, is very clear for the user.

Regarding which advanced parameters (not limited to the protocol) should be exposed, we need to think about a long-term design. Different users may need different "advanced parameters" for their work. There are two ways:
- add a new parameter every time the user requests it.
- expose all the PW parameters in the advanced setting.

I prefer the second way. but we need to find a nice way to do that, since there are a lot of parameters. For example, provide a "+" button to add new field, so that the user can input as many as "key"-"value" for their needs.

**Comment by cpignedoli** [comment]
Hi Xing, sure we have to be careful what we expose and how, and I would expose only pre-determined parameters (so according to precise moderate or..)
I have two examples in mind: phonons for real systems (100 150 atoms) you can really need to push convergence well beyond 100* "precise standards"

Energy differences for e.g. adsorption energy: if you have a molecule on a substrate (30 atoms molecule 400 atoms substrate e.g.) you do not express the adsorption energy as energy per atom and you want your energies to be in absolute quite accurate

**Comment by edan-bainglass** [comment]
Not a QE app user. I have a question - on selection of one of the three protocols (fast, moderate, precise), what is set? What changes?

**Comment by AndresOrtegaGuerrero** [comment]
So all these changes are at the `aiida-quantumespresso`  ,  here are the protocols , https://github.com/aiidateam/aiida-quantumespresso/tree/main/src/aiida_quantumespresso/workflows/protocols/pw 

and usually, it really depends on the logic of the workflow, https://github.com/aiidateam/aiida-quantumespresso/tree/main/src/aiida_quantumespresso/workflows/pw

in some cases the parameters can be changed directly , like updating a dictionary, for others a lil more complicated

**Comment by AndresOrtegaGuerrero** [comment]
In order to solve our issues for geometry optimization with tight convergence criteria, I decided (as a temporary solution) to just implement the threshols from pw.x in the QE App 

<img width="1008" alt="image" src="https://github.com/aiidalab/aiidalab-qe/assets/34098967/7e53ad28-34f3-458e-871d-60cfdbdd10fb">

**Comment by AndresOrtegaGuerrero** [comment]
This was resolved in #699
