### ISSUE TITLE
Add support for charge analysis

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#618]
**Is your feature request related to a problem? Please describe.**
From the experimental group, they may interested in the 

- [x] Bader charge

We could add plugins for these.

I moved `Charge density` to another issue.

**Comment by PNOGillespie** [comment]
I'll add some (hopefully useful) context from previous experience of partially succeeding at this with AiiDA-QE:

Charge density can be computed with a `PpCalculation` run, which is still supported in AiiDA-QE and one simply has to give the correct value for `plot_num` (e.g. `plot_num = 0` for valence charge) and also for `iflag` and `output_format`. The parser for a `PpCalculation` should return the results in a JSON file. Last time I tried this, I decided to just download the cube files I generated from their working directories on the remote machine instead of using the JSON file since I wasn't sure how to convert JSON to cube format.

For Bader charges, I used the pre-compiled executable from [Richard Bader's group website](http://theory.cm.utexas.edu/henkelman/code/bader/) which worked directly in the terminal and accepts Gaussian cube files as input. It's possible that there are "fancier" Bader charge analysis programs out there, but this one should be transferable to different Linux/Mac systems and run quite efficiently (I clocked it at ~1 second for a 16 atom unit cell with 100 valence electrons).

The way I see it, this could be better integrated to AiiDA/AiiDALab if:
1. There is some way to convert JSON (or the `ArrayData` returned by the CalcJob node) to Gaussian cube format and get it to work in AiiDA.
2. The Bader executable can be made to work with AiiDA-Shell, or something similar.

Hope this helps.

**Comment by superstar54** [comment]
Thanks, @PNOGillespie, for the suggestion!

The bader charge calcjob, workchain and qeapp plugin are implemented in this [repository](https://github.com/superstar54/aiida-bader). It uses bader code from Henkelman group. The cube file is used directly.

**Comment by superstar54** [comment]
I closed this issue as the `bader change` is implemented. and I moved the `Charge density` part to another issue, #677 .
