### ISSUE TITLE
multifactor app for cscs

### ISSUE THREAD

**Issue by bio15** [aiidalab/aiidalab-qe#629]
The MFA app is not working for me, logging manually through the console works.

**Comment by superstar54** [comment]
@bio15 and I go through a test XPS calculation using QE App. After logging in manually, the MFA app shows the key is updated and will expire in 23 hours.

**Comment by AndresOrtegaGuerrero** [comment]
@superstar54 Should this issue be in [aiidalab-mfa-cscs](https://github.com/aiidalab/aiidalab-mfa-cscs) ?

**Comment by unkcpz** [comment]
Hi @bio15, @superstar54  can you describe the problem, why it is not working? I remember @superstar54 test one week ago and seems it is working? 
As @AndresOrtegaGuerrero mentioned, it is an issue of `aiidalab-mfa-cscs`, please open an issue and have discussion there.

**Comment by superstar54** [comment]
I will confirm with @bio15 tomorrow when we meet in person. 

Yes, it's an issue of `aiidalab-mfa-cscs`, but I think it is fine for a user to create an issue here. The user doesn't know the other repos as we do. I think any issue the user encounters when using the app can be put here, and it's not necessary to move to other repos, so that the following user can search.

**Comment by unkcpz** [comment]
> Yes, it's an issue of aiidalab-mfa-cscs, but I think it is fine for a user to create an issue here. 

Sure! We can manage the issues by ourself.

**Comment by superstar54** [comment]
After meeting with @bio15 in person, we tried it in a fresh docker container. The app works.

**Comment by unkcpz** [comment]
Anything unclear or did you made a record or similar thing for us to improve the app?
