### ISSUE TITLE
legend is not visible or only partially visible in narrow windows

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-qe#820]
For narrow windows, especially if bands+PDOS are shown, the legend is not visible or only partially visible.
- Question: is it possible to call a JS function to know the window size, and show selectively a message? so that if the window is < XXX pixels (XX to check but it’s easy to see), an additional message is shown: “NOTE: the window is too narrow - enlarge it to see also the legend and toggle the plot lines.”. This needs to be show just above the plot (below the message discussed above on hovering to show the home button etc.”
- If it’s difficult, communicate back to Carlo & Giovanni who can provide a sentence to show always

**Comment by AndresOrtegaGuerrero** [comment]
@cpignedoli  Could you provide a snapshot to understand a lil better this behaviour ?

**Comment by cpignedoli** [comment]
Could be browser dependent, in my browser (crome) it's less of a problem because tehre are no "intermediate cases" : 
The plot should look like:
<img width="621" alt="image" src="https://github.com/user-attachments/assets/ab438a97-4893-4f87-9c50-91b4bf3f873d">


It is probably obvious that the user should enlarge the window in case the plot looks like:

<img width="494" alt="image" src="https://github.com/user-attachments/assets/4d7ba66e-a112-489c-ac64-06bfb222989f">

**But there could be cases (we have seen it from the pc of @giovannipizzi ) where for example you miss "just the legend" and the user may not know there is a legend...**

The idea is: to know how many pixels we need to visualize correctly the plot, and if the window is smaller we prompt a warning message like: "Please enlarge the browser window, a portion of the plot is missing"

**Comment by superstar54** [comment]
You can debug on devices with different screen sizes inside the browser. Press `F12`, and toggle the device toolbar,



https://github.com/user-attachments/assets/41eb6b41-ffe0-42ab-ad7d-bb8b4b8972ed
