### ISSUE TITLE
If you don't relax the structure, show a tab "Initial structure"

### ISSUE THREAD

**Issue by edan-bainglass** [aiidalab/aiidalab-qe#993]
This is useful because if the user might have to filter by atom index, and it's important to have it close to the results

Also:
- [ ] Rename the tab when some relaxation has been performed to "Relaxed structure" (instead of Final Geometry), note also capitalization here!

**Comment by edan-bainglass** [comment]
@giovannipizzi can you say more about this one? At the moment, I don't see the need for this, but maybe I'm missing some use case. Let's discuss.

**Comment by giovannipizzi** [comment]
If I do a PDOS and I want to select by atom index, how do I know which integers to write? I need a tab close to the results with the structure. I have this in case of relaxation, I don't in case of a scf.
One could go to the input, but one has to do things in two different ways depending on one specific input, it's non obvious and it's trickier (I think) to know where to search back in the tabs.

I think it should just be another tab identical to the relaxed structure, but with a different name and getting the stucture form the inputs instead of the outputs of the workflow. @cpignedoli what do you think?

**Comment by cpignedoli** [comment]
Correct @giovannipizzi , I did not notice this

**Comment by edan-bainglass** [comment]
For now, I will add a note regarding where the user can find atom indices. We can revisit this issue when we meet in January.
